from .fight import go_fight
from .deposit_items import go_deposit_items
from .equip import go_equip
from .craft import go_craft
from .gather import go_gather
from .deposit_gold import go_deposit_gold
from .withdraw_items import go_withdraw_items
from .complete_task import go_complete_task
from .get_new_task import go_get_new_task
from .trade_task import go_trade_task
from .produce import go_produce